/**
 * Mednet EDC API
 * The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
 *
 * The version of the OpenAPI document: 1.3.6
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIComponents_schemas_Interval_forms_item.h
 *
 * 
 */

#ifndef OAIComponents_schemas_Interval_forms_item_H
#define OAIComponents_schemas_Interval_forms_item_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIComponents_schemas_Interval_forms_item : public OAIObject {
public:
    OAIComponents_schemas_Interval_forms_item();
    OAIComponents_schemas_Interval_forms_item(QString json);
    ~OAIComponents_schemas_Interval_forms_item() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint32 getFormId() const;
    void setFormId(const qint32 &form_id);
    bool is_form_id_Set() const;
    bool is_form_id_Valid() const;

    QString getFormKey() const;
    void setFormKey(const QString &form_key);
    bool is_form_key_Set() const;
    bool is_form_key_Valid() const;

    QString getFormName() const;
    void setFormName(const QString &form_name);
    bool is_form_name_Set() const;
    bool is_form_name_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint32 m_form_id;
    bool m_form_id_isSet;
    bool m_form_id_isValid;

    QString m_form_key;
    bool m_form_key_isSet;
    bool m_form_key_isValid;

    QString m_form_name;
    bool m_form_name_isSet;
    bool m_form_name_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIComponents_schemas_Interval_forms_item)

#endif // OAIComponents_schemas_Interval_forms_item_H
