/**
 * Mednet EDC API
 * The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
 *
 * The version of the OpenAPI document: 1.3.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class User (
  /* Unique user ID (UUID) */
  userId: Option[String] = None,
  /* User login name */
  login: Option[String] = None,
  /* User first name */
  firstName: Option[String] = None,
  /* User last name */
  lastName: Option[String] = None,
  /* User email address */
  email: Option[String] = None,
  /* Whether the user is active in the given study */
  userActiveInStudy: Option[Boolean] = None,
  /* Roles that the user has in the study */
  roles: Option[Seq[Role]] = None
) extends ApiModel

