/**
 * Mednet EDC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Role { 
    /**
     * Timestamp when the role assignment was created (as [year, month, day, hour, minute, second, nanosecond])
     */
    dateCreated?: Array<number>;
    /**
     * Timestamp when the role assignment was last modified
     */
    dateModified?: Array<number>;
    /**
     * Unique role ID (UUID)
     */
    roleId?: string;
    /**
     * Community ID or level associated with the role
     */
    communityId?: number;
    /**
     * Name of the role
     */
    name?: string;
    /**
     * Description of the role
     */
    description?: string;
    /**
     * Role level or hierarchy
     */
    level?: number;
    /**
     * Role type/category
     */
    type?: string;
    /**
     * Whether the role is inactive
     */
    inactive?: boolean;
}

