/**
 * Mednet EDC API
 * The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
 *
 * The version of the OpenAPI document: 1.3.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Role {
    /**
    * Timestamp when the role assignment was created (as [year, month, day, hour, minute, second, nanosecond])
    */
    'dateCreated'?: Array<number>;
    /**
    * Timestamp when the role assignment was last modified
    */
    'dateModified'?: Array<number>;
    /**
    * Unique role ID (UUID)
    */
    'roleId'?: string;
    /**
    * Community ID or level associated with the role
    */
    'communityId'?: number;
    /**
    * Name of the role
    */
    'name'?: string;
    /**
    * Description of the role
    */
    'description'?: string;
    /**
    * Role level or hierarchy
    */
    'level'?: number;
    /**
    * Role type/category
    */
    'type'?: string;
    /**
    * Whether the role is inactive
    */
    'inactive'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dateCreated",
            "baseName": "dateCreated",
            "type": "Array<number>"
        },
        {
            "name": "dateModified",
            "baseName": "dateModified",
            "type": "Array<number>"
        },
        {
            "name": "roleId",
            "baseName": "roleId",
            "type": "string"
        },
        {
            "name": "communityId",
            "baseName": "communityId",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "number"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "inactive",
            "baseName": "inactive",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return Role.attributeTypeMap;
    }
}

