--[[
  Mednet EDC API

  The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 

  The version of the OpenAPI document: 1.3.6
  
  Generated by: https://openapi-generator.tech
]]

-- record_revision class
local record_revision = {}
local record_revision_mt = {
	__name = "record_revision";
	__index = record_revision;
}

local function cast_record_revision(t)
	return setmetatable(t, record_revision_mt)
end

local function new_record_revision(study_key, record_revision_id, record_id, record_oid, record_revision, data_revision, record_status, subject_id, subject_oid, subject_key, site_id, form_key, interval_id, role, user, reason_for_change, deleted, date_created)
	return cast_record_revision({
		["studyKey"] = study_key;
		["recordRevisionId"] = record_revision_id;
		["recordId"] = record_id;
		["recordOid"] = record_oid;
		["recordRevision"] = record_revision;
		["dataRevision"] = data_revision;
		["recordStatus"] = record_status;
		["subjectId"] = subject_id;
		["subjectOid"] = subject_oid;
		["subjectKey"] = subject_key;
		["siteId"] = site_id;
		["formKey"] = form_key;
		["intervalId"] = interval_id;
		["role"] = role;
		["user"] = user;
		["reasonForChange"] = reason_for_change;
		["deleted"] = deleted;
		["dateCreated"] = date_created;
	})
end

return {
	cast = cast_record_revision;
	new = new_record_revision;
}
