=begin comment

Mednet EDC API

The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 

The version of the OpenAPI document: 1.3.6

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::SitesApi');

my $api = WWW::OpenAPIClient::SitesApi->new();
isa_ok($api, 'WWW::OpenAPIClient::SitesApi');

#
# list_sites test
#
# uncomment below and update the test
#my $list_sites_study_key = undef; # replace NULL with a proper value
#my $list_sites_page = undef; # replace NULL with a proper value
#my $list_sites_size = undef; # replace NULL with a proper value
#my $list_sites_sort = undef; # replace NULL with a proper value
#my $list_sites_filter = undef; # replace NULL with a proper value
#my $list_sites_result = $api->list_sites(study_key => $list_sites_study_key, page => $list_sites_page, size => $list_sites_size, sort => $list_sites_sort, filter => $list_sites_filter);


done_testing();
