/**
 * Mednet EDC API
 * The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
 *
 * The version of the OpenAPI document: 1.3.6
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAI_OAIRecordsApi_H
#define OAI_OAIRecordsApi_H

#include "OAIHelpers.h"
#include "OAIHttpRequest.h"
#include "OAIServerConfiguration.h"
#include "OAIOauth.h"

#include "OAIComponents_schemas_RecordCreateRequest_item.h"
#include "OAIInline_object.h"
#include "OAIInline_object_1.h"
#include "OAIInline_object_2.h"
#include "OAIInline_object_3.h"
#include "OAIInline_object_4.h"
#include "OAIInline_object_5.h"
#include "OAIRecordJobStatus.h"
#include "OAIRecordList.h"
#include <QString>

#include <QObject>
#include <QByteArray>
#include <QStringList>
#include <QList>
#include <QNetworkAccessManager>

namespace OpenAPI {

class OAIRecordsApi : public QObject {
    Q_OBJECT

public:
    OAIRecordsApi(const int timeOut = 0);
    ~OAIRecordsApi();

    void initializeServerConfigs();
    int setDefaultServerValue(int serverIndex,const QString &operation, const QString &variable,const QString &val);
    void setServerIndex(const QString &operation, int serverIndex);
    void setApiKey(const QString &apiKeyName, const QString &apiKey);
    void setBearerToken(const QString &token);
    void setUsername(const QString &username);
    void setPassword(const QString &password);
    void setTimeOut(const int timeOut);
    void setWorkingDirectory(const QString &path);
    void setNetworkAccessManager(QNetworkAccessManager* manager);
    int addServerConfiguration(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, OAIServerVariable> &variables = QMap<QString, OAIServerVariable>());
    void setNewServerForAllOperations(const QUrl &url, const QString &description = "", const QMap<QString, OAIServerVariable> &variables =  QMap<QString, OAIServerVariable>());
    void setNewServer(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, OAIServerVariable> &variables =  QMap<QString, OAIServerVariable>());
    void addHeaders(const QString &key, const QString &value);
    void enableRequestCompression();
    void enableResponseCompression();
    void abortRequests();
    QString getParamStylePrefix(const QString &style);
    QString getParamStyleSuffix(const QString &style);
    QString getParamStyleDelimiter(const QString &style, const QString &name, bool isExplode);

    /**
    * @param[in]  study_key QString [required]
    * @param[in]  oai_components_schemas_record_create_request_item QList<OAIComponents_schemas_RecordCreateRequest_item> [required]
    */
    virtual void createRecords(const QString &study_key, const QList<OAIComponents_schemas_RecordCreateRequest_item> &oai_components_schemas_record_create_request_item);

    /**
    * @param[in]  study_key QString [required]
    * @param[in]  page qint32 [optional]
    * @param[in]  size qint32 [optional]
    * @param[in]  sort QString [optional]
    * @param[in]  filter QString [optional]
    * @param[in]  record_data_filter QString [optional]
    */
    virtual void listRecords(const QString &study_key, const ::OpenAPI::OptionalParam<qint32> &page = ::OpenAPI::OptionalParam<qint32>(), const ::OpenAPI::OptionalParam<qint32> &size = ::OpenAPI::OptionalParam<qint32>(), const ::OpenAPI::OptionalParam<QString> &sort = ::OpenAPI::OptionalParam<QString>(), const ::OpenAPI::OptionalParam<QString> &filter = ::OpenAPI::OptionalParam<QString>(), const ::OpenAPI::OptionalParam<QString> &record_data_filter = ::OpenAPI::OptionalParam<QString>());


private:
    QMap<QString,int> _serverIndices;
    QMap<QString,QList<OAIServerConfiguration>> _serverConfigs;
    QMap<QString, QString> _apiKeys;
    QString _bearerToken;
    QString _username;
    QString _password;
    int _timeOut;
    QString _workingDirectory;
    QNetworkAccessManager* _manager;
    QMap<QString, QString> _defaultHeaders;
    bool _isResponseCompressionEnabled;
    bool _isRequestCompressionEnabled;
    OAIHttpRequestInput _latestInput;
    OAIHttpRequestWorker *_latestWorker;
    QStringList _latestScope;
    OauthCode _authFlow;
    OauthImplicit _implicitFlow;
    OauthCredentials _credentialFlow;
    OauthPassword _passwordFlow;
    int _OauthMethod = 0;

    void createRecordsCallback(OAIHttpRequestWorker *worker);
    void listRecordsCallback(OAIHttpRequestWorker *worker);

Q_SIGNALS:

    void createRecordsSignal(OAIRecordJobStatus summary);
    void listRecordsSignal(OAIRecordList summary);


    void createRecordsSignalFull(OAIHttpRequestWorker *worker, OAIRecordJobStatus summary);
    void listRecordsSignalFull(OAIHttpRequestWorker *worker, OAIRecordList summary);

    Q_DECL_DEPRECATED_X("Use createRecordsSignalError() instead")
    void createRecordsSignalE(OAIRecordJobStatus summary, QNetworkReply::NetworkError error_type, QString error_str);
    void createRecordsSignalError(OAIRecordJobStatus summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use listRecordsSignalError() instead")
    void listRecordsSignalE(OAIRecordList summary, QNetworkReply::NetworkError error_type, QString error_str);
    void listRecordsSignalError(OAIRecordList summary, QNetworkReply::NetworkError error_type, const QString &error_str);

    Q_DECL_DEPRECATED_X("Use createRecordsSignalErrorFull() instead")
    void createRecordsSignalEFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void createRecordsSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use listRecordsSignalErrorFull() instead")
    void listRecordsSignalEFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void listRecordsSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);

    void abortRequestsSignal();
    void allPendingRequestsCompleted();

public Q_SLOTS:
    void tokenAvailable();
};

} // namespace OpenAPI
#endif
