/**
 * Mednet EDC API
 * The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
 *
 * The version of the OpenAPI document: 1.3.6
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIRecordRevisionList.h
 *
 * 
 */

#ifndef OAIRecordRevisionList_H
#define OAIRecordRevisionList_H

#include <QJsonObject>

#include "OAIMetadata.h"
#include "OAIPagination.h"
#include "OAIRecordRevision.h"
#include <QList>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIMetadata;
class OAIPagination;
class OAIRecordRevision;

class OAIRecordRevisionList : public OAIObject {
public:
    OAIRecordRevisionList();
    OAIRecordRevisionList(QString json);
    ~OAIRecordRevisionList() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAIMetadata getMetadata() const;
    void setMetadata(const OAIMetadata &metadata);
    bool is_metadata_Set() const;
    bool is_metadata_Valid() const;

    OAIPagination getPagination() const;
    void setPagination(const OAIPagination &pagination);
    bool is_pagination_Set() const;
    bool is_pagination_Valid() const;

    QList<OAIRecordRevision> getData() const;
    void setData(const QList<OAIRecordRevision> &data);
    bool is_data_Set() const;
    bool is_data_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAIMetadata m_metadata;
    bool m_metadata_isSet;
    bool m_metadata_isValid;

    OAIPagination m_pagination;
    bool m_pagination_isSet;
    bool m_pagination_isValid;

    QList<OAIRecordRevision> m_data;
    bool m_data_isSet;
    bool m_data_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIRecordRevisionList)

#endif // OAIRecordRevisionList_H
