/**
 * Mednet EDC API
 * The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
 *
 * The version of the OpenAPI document: 1.3.6
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAISort.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAISort::OAISort(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAISort::OAISort() {
    this->initializeModel();
}

OAISort::~OAISort() {}

void OAISort::initializeModel() {

    m_property_isSet = false;
    m_property_isValid = false;

    m_direction_isSet = false;
    m_direction_isValid = false;
}

void OAISort::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAISort::fromJsonObject(QJsonObject json) {

    m_property_isValid = ::OpenAPI::fromJsonValue(m_property, json[QString("property")]);
    m_property_isSet = !json[QString("property")].isNull() && m_property_isValid;

    m_direction_isValid = ::OpenAPI::fromJsonValue(m_direction, json[QString("direction")]);
    m_direction_isSet = !json[QString("direction")].isNull() && m_direction_isValid;
}

QString OAISort::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAISort::asJsonObject() const {
    QJsonObject obj;
    if (m_property_isSet) {
        obj.insert(QString("property"), ::OpenAPI::toJsonValue(m_property));
    }
    if (m_direction_isSet) {
        obj.insert(QString("direction"), ::OpenAPI::toJsonValue(m_direction));
    }
    return obj;
}

QString OAISort::getProperty() const {
    return m_property;
}
void OAISort::setProperty(const QString &property) {
    m_property = property;
    m_property_isSet = true;
}

bool OAISort::is_property_Set() const{
    return m_property_isSet;
}

bool OAISort::is_property_Valid() const{
    return m_property_isValid;
}

QString OAISort::getDirection() const {
    return m_direction;
}
void OAISort::setDirection(const QString &direction) {
    m_direction = direction;
    m_direction_isSet = true;
}

bool OAISort::is_direction_Set() const{
    return m_direction_isSet;
}

bool OAISort::is_direction_Valid() const{
    return m_direction_isValid;
}

bool OAISort::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_property_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_direction_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAISort::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
