# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""RecordRevisionList

    RecordRevisionList(;
        metadata=nothing,
        pagination=nothing,
        data=nothing,
    )

    - metadata::Metadata
    - pagination::Pagination
    - data::Vector{RecordRevision}
"""
Base.@kwdef mutable struct RecordRevisionList <: OpenAPI.APIModel
    metadata = nothing # spec type: Union{ Nothing, Metadata }
    pagination = nothing # spec type: Union{ Nothing, Pagination }
    data::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{RecordRevision} }

    function RecordRevisionList(metadata, pagination, data, )
        o = new(metadata, pagination, data, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type RecordRevisionList

const _property_types_RecordRevisionList = Dict{Symbol,String}(Symbol("metadata")=>"Metadata", Symbol("pagination")=>"Pagination", Symbol("data")=>"Vector{RecordRevision}", )
OpenAPI.property_type(::Type{ RecordRevisionList }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_RecordRevisionList[name]))}

function OpenAPI.check_required(o::RecordRevisionList)
    true
end

function OpenAPI.validate_properties(o::RecordRevisionList)
    OpenAPI.validate_property(RecordRevisionList, Symbol("metadata"), o.metadata)
    OpenAPI.validate_property(RecordRevisionList, Symbol("pagination"), o.pagination)
    OpenAPI.validate_property(RecordRevisionList, Symbol("data"), o.data)
end

function OpenAPI.validate_property(::Type{ RecordRevisionList }, name::Symbol, val)



end
