# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""inline_object

    InlineObject(;
        metadata=nothing,
    )

    - metadata::Metadata
"""
Base.@kwdef mutable struct InlineObject <: OpenAPI.APIModel
    metadata = nothing # spec type: Union{ Nothing, Metadata }

    function InlineObject(metadata, )
        o = new(metadata, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type InlineObject

const _property_types_InlineObject = Dict{Symbol,String}(Symbol("metadata")=>"Metadata", )
OpenAPI.property_type(::Type{ InlineObject }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_InlineObject[name]))}

function OpenAPI.check_required(o::InlineObject)
    true
end

function OpenAPI.validate_properties(o::InlineObject)
    OpenAPI.validate_property(InlineObject, Symbol("metadata"), o.metadata)
end

function OpenAPI.validate_property(::Type{ InlineObject }, name::Symbol, val)

end
