# #Mednet EDC API
#
##The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
#
#The version of the OpenAPI document: 1.3.6
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.14.0
#

require "../spec_helper"

# Unit tests for OpenAPIClient::JobsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
Spectator.describe "JobsApi" do
  describe "test an instance of JobsApi" do
    it "should create an instance of JobsApi" do
      api_instance = OpenAPIClient::JobsApi.new
      expect(api_instance).to be_instance_of(OpenAPIClient::JobsApi)
    end
  end

  # unit tests for get_job_status
  # Retrieve job status by batch ID
  # @param study_key Study key identifying the study context for the request
  # @param batch_id Batch ID of the job to retrieve
  # @param [Hash] opts the optional parameters
  # @return [Job]
  describe "get_job_status test" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
