--[[
  Mednet EDC API

  The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 

  The version of the OpenAPI document: 1.3.6
  
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for openapiclient.model.components_schemas_metadata_error
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("components_schemas_metadata_error", function()
  local openapiclient_components_schemas_metadata_error = require "openapiclient.model.components_schemas_metadata_error"

  -- unit tests for the property 'message'
  describe("property message test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
