//
// RecordsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class RecordsAPI {

    /**
     Add new record or update subject/record data
     
     - parameter studyKey: (path) Study key identifying the study context for the request 
     - parameter componentsSchemasRecordCreateRequestItem: (body) An array of record objects defining the operation to perform (subject registration, record creation, or scheduled record update). 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RecordJobStatus
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createRecords(studyKey: String, componentsSchemasRecordCreateRequestItem: [ComponentsSchemasRecordCreateRequestItem], apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> RecordJobStatus {
        return try await createRecordsWithRequestBuilder(studyKey: studyKey, componentsSchemasRecordCreateRequestItem: componentsSchemasRecordCreateRequestItem, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Add new record or update subject/record data
     - POST /studies/{studyKey}/records
     - API Key:
       - type: apiKey x-api-key (HEADER)
       - name: apiKeyAuth
     - API Key:
       - type: apiKey x-imn-security-key (HEADER)
       - name: securityKeyAuth
     - parameter studyKey: (path) Study key identifying the study context for the request 
     - parameter componentsSchemasRecordCreateRequestItem: (body) An array of record objects defining the operation to perform (subject registration, record creation, or scheduled record update). 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<RecordJobStatus> 
     */
    open class func createRecordsWithRequestBuilder(studyKey: String, componentsSchemasRecordCreateRequestItem: [ComponentsSchemasRecordCreateRequestItem], apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<RecordJobStatus> {
        var localVariablePath = "/studies/{studyKey}/records"
        let studyKeyPreEscape = "\(APIHelper.mapValueToPathItem(studyKey))"
        let studyKeyPostEscape = studyKeyPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{studyKey}", with: studyKeyPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: componentsSchemasRecordCreateRequestItem, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RecordJobStatus>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List records (eCRF instances) in a study
     
     - parameter studyKey: (path) Study key identifying the study context for the request 
     - parameter page: (query) Page index to retrieve (0-based) (optional, default to 0)
     - parameter size: (query) Number of items to return per page (max 500) (optional, default to 25)
     - parameter sort: (query) Sorting criteria in the format &#x60;property,ASC&#x60; or &#x60;property,DESC&#x60;. Can be repeated. (optional)
     - parameter filter: (query) Optional filter criteria to apply, in the format &#x60;attribute&#x3D;&#x3D;value&#x60; with support for &gt;, &gt;&#x3D;, &lt;, &lt;&#x3D;, !&#x3D;. Multiple criteria can be combined with &#x60;;&#x60; (AND) or &#x60;,&#x60; (OR). (optional)
     - parameter recordDataFilter: (query) Optional filter criteria to apply on recordData fields (question responses). Supports &#x3D;&#x3D;, !&#x3D;, &lt;, &lt;&#x3D;, &gt;, &gt;&#x3D;, &#x3D;~ (contains) and can combine multiple criteria with &#x60;;&#x60; (AND) or &#x60;,&#x60; (OR). (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RecordList
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listRecords(studyKey: String, page: Int? = nil, size: Int? = nil, sort: String? = nil, filter: String? = nil, recordDataFilter: String? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> RecordList {
        return try await listRecordsWithRequestBuilder(studyKey: studyKey, page: page, size: size, sort: sort, filter: filter, recordDataFilter: recordDataFilter, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List records (eCRF instances) in a study
     - GET /studies/{studyKey}/records
     - API Key:
       - type: apiKey x-api-key (HEADER)
       - name: apiKeyAuth
     - API Key:
       - type: apiKey x-imn-security-key (HEADER)
       - name: securityKeyAuth
     - parameter studyKey: (path) Study key identifying the study context for the request 
     - parameter page: (query) Page index to retrieve (0-based) (optional, default to 0)
     - parameter size: (query) Number of items to return per page (max 500) (optional, default to 25)
     - parameter sort: (query) Sorting criteria in the format &#x60;property,ASC&#x60; or &#x60;property,DESC&#x60;. Can be repeated. (optional)
     - parameter filter: (query) Optional filter criteria to apply, in the format &#x60;attribute&#x3D;&#x3D;value&#x60; with support for &gt;, &gt;&#x3D;, &lt;, &lt;&#x3D;, !&#x3D;. Multiple criteria can be combined with &#x60;;&#x60; (AND) or &#x60;,&#x60; (OR). (optional)
     - parameter recordDataFilter: (query) Optional filter criteria to apply on recordData fields (question responses). Supports &#x3D;&#x3D;, !&#x3D;, &lt;, &lt;&#x3D;, &gt;, &gt;&#x3D;, &#x3D;~ (contains) and can combine multiple criteria with &#x60;;&#x60; (AND) or &#x60;,&#x60; (OR). (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<RecordList> 
     */
    open class func listRecordsWithRequestBuilder(studyKey: String, page: Int? = nil, size: Int? = nil, sort: String? = nil, filter: String? = nil, recordDataFilter: String? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<RecordList> {
        var localVariablePath = "/studies/{studyKey}/records"
        let studyKeyPreEscape = "\(APIHelper.mapValueToPathItem(studyKey))"
        let studyKeyPostEscape = studyKeyPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{studyKey}", with: studyKeyPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "size": (wrappedValue: size?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "sort": (wrappedValue: sort?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "filter": (wrappedValue: filter?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "recordDataFilter": (wrappedValue: recordDataFilter?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RecordList>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
