/**
 * Mednet EDC API
 * The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
 *
 * The version of the OpenAPI document: 1.3.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model


case class Site(
  /* Unique study key */
  studyKey: Option[String] = None,
  /* Unique site ID */
  siteId: Option[Int] = None,
  /* Name of the site */
  siteName: Option[String] = None,
  /* Enrollment status of the site */
  siteEnrollmentStatus: Option[String] = None,
  /* Date when this site was created */
  dateCreated: Option[String] = None,
  /* Date when this site was last modified */
  dateModified: Option[String] = None
)

