//
// Keyword.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Keyword: Codable {
    /// Name of the keyword
    public var keywordName: String?
    /// Key of the keyword (short code)
    public var keywordKey: String?
    /// Internal keyword ID
    public var keywordId: Int?
    /// Date when this keyword was added
    public var dateAdded: String?

    public init(keywordName: String? = nil, keywordKey: String? = nil, keywordId: Int? = nil, dateAdded: String? = nil) {
        self.keywordName = keywordName
        self.keywordKey = keywordKey
        self.keywordId = keywordId
        self.dateAdded = dateAdded
    }
}
