/** Mednet EDC API
  * The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
  *
  * The version of the OpenAPI document: 1.3.6
  * Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  * Do not edit the class manually.
  */
package org.openapitools.client.models

import io.circe.*
import io.circe.syntax.*
import io.circe.{Decoder, Encoder}


/** Error details if an error occurred
  * @param message Error message describing the issue
  */
case class ComponentsSchemasMetadataError(
    message: Option[String] = None
)
  
object ComponentsSchemasMetadataError {
  given encoderComponentsSchemasMetadataError: Encoder[ComponentsSchemasMetadataError] = Encoder.instance { t =>
    Json.fromFields{
      Seq(
        t.message.map(v => "message" -> v.asJson)
      ).flatten
    }
  }
  given decoderComponentsSchemasMetadataError: Decoder[ComponentsSchemasMetadataError] = Decoder.instance { c =>
    for {
      message <- c.downField("message").as[Option[String]]
    } yield ComponentsSchemasMetadataError(
      message = message
    )
  }
}

