# NOTE: This file is auto generated by OpenAPI Generator 7.14.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MednetEDCAPI.Model.Coding do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :studyKey,
    :siteName,
    :siteId,
    :subjectId,
    :subjectKey,
    :formId,
    :formName,
    :formKey,
    :revision,
    :recordId,
    :variable,
    :value,
    :codingId,
    :code,
    :codedBy,
    :reason,
    :dictionaryName,
    :dictionaryVersion,
    :dateCoded
  ]

  @type t :: %__MODULE__{
    :studyKey => String.t | nil,
    :siteName => String.t | nil,
    :siteId => integer() | nil,
    :subjectId => integer() | nil,
    :subjectKey => String.t | nil,
    :formId => integer() | nil,
    :formName => String.t | nil,
    :formKey => String.t | nil,
    :revision => integer() | nil,
    :recordId => integer() | nil,
    :variable => String.t | nil,
    :value => String.t | nil,
    :codingId => integer() | nil,
    :code => String.t | nil,
    :codedBy => String.t | nil,
    :reason => String.t | nil,
    :dictionaryName => String.t | nil,
    :dictionaryVersion => String.t | nil,
    :dateCoded => String.t | nil
  }

  def decode(value) do
    value
  end
end

