# NOTE: This file is auto generated by OpenAPI Generator 7.14.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MednetEDCAPI.Model.QueryList do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :metadata,
    :pagination,
    :data
  ]

  @type t :: %__MODULE__{
    :metadata => MednetEDCAPI.Model.Metadata.t | nil,
    :pagination => MednetEDCAPI.Model.Pagination.t | nil,
    :data => [MednetEDCAPI.Model.Query.t] | nil
  }

  alias MednetEDCAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:metadata, :struct, MednetEDCAPI.Model.Metadata)
     |> Deserializer.deserialize(:pagination, :struct, MednetEDCAPI.Model.Pagination)
     |> Deserializer.deserialize(:data, :list, MednetEDCAPI.Model.Query)
  end
end

