<?php
/**
 * Record
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mednet EDC API
 *
 * The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API.
 *
 * The version of the OpenAPI document: 1.3.6
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Record Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Record implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Record';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'study_key' => 'string',
        'interval_id' => 'int',
        'form_id' => 'int',
        'form_key' => 'string',
        'site_id' => 'int',
        'record_id' => 'int',
        'record_oid' => 'string',
        'record_type' => 'string',
        'record_status' => 'string',
        'deleted' => 'bool',
        'date_created' => 'string',
        'date_modified' => 'string',
        'subject_id' => 'int',
        'subject_oid' => 'string',
        'subject_key' => 'string',
        'visit_id' => 'int',
        'parent_record_id' => 'int',
        'keywords' => '\OpenAPI\Client\Model\Keyword[]',
        'record_data' => 'array<string,mixed>'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'study_key' => null,
        'interval_id' => null,
        'form_id' => null,
        'form_key' => null,
        'site_id' => null,
        'record_id' => null,
        'record_oid' => null,
        'record_type' => null,
        'record_status' => null,
        'deleted' => null,
        'date_created' => null,
        'date_modified' => null,
        'subject_id' => null,
        'subject_oid' => null,
        'subject_key' => null,
        'visit_id' => null,
        'parent_record_id' => null,
        'keywords' => null,
        'record_data' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'study_key' => false,
        'interval_id' => false,
        'form_id' => false,
        'form_key' => false,
        'site_id' => false,
        'record_id' => false,
        'record_oid' => false,
        'record_type' => false,
        'record_status' => false,
        'deleted' => false,
        'date_created' => false,
        'date_modified' => false,
        'subject_id' => false,
        'subject_oid' => false,
        'subject_key' => false,
        'visit_id' => false,
        'parent_record_id' => false,
        'keywords' => false,
        'record_data' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'study_key' => 'studyKey',
        'interval_id' => 'intervalId',
        'form_id' => 'formId',
        'form_key' => 'formKey',
        'site_id' => 'siteId',
        'record_id' => 'recordId',
        'record_oid' => 'recordOid',
        'record_type' => 'recordType',
        'record_status' => 'recordStatus',
        'deleted' => 'deleted',
        'date_created' => 'dateCreated',
        'date_modified' => 'dateModified',
        'subject_id' => 'subjectId',
        'subject_oid' => 'subjectOid',
        'subject_key' => 'subjectKey',
        'visit_id' => 'visitId',
        'parent_record_id' => 'parentRecordId',
        'keywords' => 'keywords',
        'record_data' => 'recordData'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'study_key' => 'setStudyKey',
        'interval_id' => 'setIntervalId',
        'form_id' => 'setFormId',
        'form_key' => 'setFormKey',
        'site_id' => 'setSiteId',
        'record_id' => 'setRecordId',
        'record_oid' => 'setRecordOid',
        'record_type' => 'setRecordType',
        'record_status' => 'setRecordStatus',
        'deleted' => 'setDeleted',
        'date_created' => 'setDateCreated',
        'date_modified' => 'setDateModified',
        'subject_id' => 'setSubjectId',
        'subject_oid' => 'setSubjectOid',
        'subject_key' => 'setSubjectKey',
        'visit_id' => 'setVisitId',
        'parent_record_id' => 'setParentRecordId',
        'keywords' => 'setKeywords',
        'record_data' => 'setRecordData'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'study_key' => 'getStudyKey',
        'interval_id' => 'getIntervalId',
        'form_id' => 'getFormId',
        'form_key' => 'getFormKey',
        'site_id' => 'getSiteId',
        'record_id' => 'getRecordId',
        'record_oid' => 'getRecordOid',
        'record_type' => 'getRecordType',
        'record_status' => 'getRecordStatus',
        'deleted' => 'getDeleted',
        'date_created' => 'getDateCreated',
        'date_modified' => 'getDateModified',
        'subject_id' => 'getSubjectId',
        'subject_oid' => 'getSubjectOid',
        'subject_key' => 'getSubjectKey',
        'visit_id' => 'getVisitId',
        'parent_record_id' => 'getParentRecordId',
        'keywords' => 'getKeywords',
        'record_data' => 'getRecordData'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('study_key', $data ?? [], null);
        $this->setIfExists('interval_id', $data ?? [], null);
        $this->setIfExists('form_id', $data ?? [], null);
        $this->setIfExists('form_key', $data ?? [], null);
        $this->setIfExists('site_id', $data ?? [], null);
        $this->setIfExists('record_id', $data ?? [], null);
        $this->setIfExists('record_oid', $data ?? [], null);
        $this->setIfExists('record_type', $data ?? [], null);
        $this->setIfExists('record_status', $data ?? [], null);
        $this->setIfExists('deleted', $data ?? [], null);
        $this->setIfExists('date_created', $data ?? [], null);
        $this->setIfExists('date_modified', $data ?? [], null);
        $this->setIfExists('subject_id', $data ?? [], null);
        $this->setIfExists('subject_oid', $data ?? [], null);
        $this->setIfExists('subject_key', $data ?? [], null);
        $this->setIfExists('visit_id', $data ?? [], null);
        $this->setIfExists('parent_record_id', $data ?? [], null);
        $this->setIfExists('keywords', $data ?? [], null);
        $this->setIfExists('record_data', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets study_key
     *
     * @return string|null
     */
    public function getStudyKey()
    {
        return $this->container['study_key'];
    }

    /**
     * Sets study_key
     *
     * @param string|null $study_key Unique study key
     *
     * @return self
     */
    public function setStudyKey($study_key)
    {
        if (is_null($study_key)) {
            throw new \InvalidArgumentException('non-nullable study_key cannot be null');
        }
        $this->container['study_key'] = $study_key;

        return $this;
    }

    /**
     * Gets interval_id
     *
     * @return int|null
     */
    public function getIntervalId()
    {
        return $this->container['interval_id'];
    }

    /**
     * Sets interval_id
     *
     * @param int|null $interval_id Interval ID (visit definition) that this record is associated with
     *
     * @return self
     */
    public function setIntervalId($interval_id)
    {
        if (is_null($interval_id)) {
            throw new \InvalidArgumentException('non-nullable interval_id cannot be null');
        }
        $this->container['interval_id'] = $interval_id;

        return $this;
    }

    /**
     * Gets form_id
     *
     * @return int|null
     */
    public function getFormId()
    {
        return $this->container['form_id'];
    }

    /**
     * Sets form_id
     *
     * @param int|null $form_id Form ID of the form this record instance belongs to
     *
     * @return self
     */
    public function setFormId($form_id)
    {
        if (is_null($form_id)) {
            throw new \InvalidArgumentException('non-nullable form_id cannot be null');
        }
        $this->container['form_id'] = $form_id;

        return $this;
    }

    /**
     * Gets form_key
     *
     * @return string|null
     */
    public function getFormKey()
    {
        return $this->container['form_key'];
    }

    /**
     * Sets form_key
     *
     * @param string|null $form_key Form key of the form for this record instance
     *
     * @return self
     */
    public function setFormKey($form_key)
    {
        if (is_null($form_key)) {
            throw new \InvalidArgumentException('non-nullable form_key cannot be null');
        }
        $this->container['form_key'] = $form_key;

        return $this;
    }

    /**
     * Gets site_id
     *
     * @return int|null
     */
    public function getSiteId()
    {
        return $this->container['site_id'];
    }

    /**
     * Sets site_id
     *
     * @param int|null $site_id Site ID associated with the record
     *
     * @return self
     */
    public function setSiteId($site_id)
    {
        if (is_null($site_id)) {
            throw new \InvalidArgumentException('non-nullable site_id cannot be null');
        }
        $this->container['site_id'] = $site_id;

        return $this;
    }

    /**
     * Gets record_id
     *
     * @return int|null
     */
    public function getRecordId()
    {
        return $this->container['record_id'];
    }

    /**
     * Sets record_id
     *
     * @param int|null $record_id Unique record ID
     *
     * @return self
     */
    public function setRecordId($record_id)
    {
        if (is_null($record_id)) {
            throw new \InvalidArgumentException('non-nullable record_id cannot be null');
        }
        $this->container['record_id'] = $record_id;

        return $this;
    }

    /**
     * Gets record_oid
     *
     * @return string|null
     */
    public function getRecordOid()
    {
        return $this->container['record_oid'];
    }

    /**
     * Sets record_oid
     *
     * @param string|null $record_oid Client-assigned record OID
     *
     * @return self
     */
    public function setRecordOid($record_oid)
    {
        if (is_null($record_oid)) {
            throw new \InvalidArgumentException('non-nullable record_oid cannot be null');
        }
        $this->container['record_oid'] = $record_oid;

        return $this;
    }

    /**
     * Gets record_type
     *
     * @return string|null
     */
    public function getRecordType()
    {
        return $this->container['record_type'];
    }

    /**
     * Sets record_type
     *
     * @param string|null $record_type Type of record (e.g., SUBJECT for subject-related forms)
     *
     * @return self
     */
    public function setRecordType($record_type)
    {
        if (is_null($record_type)) {
            throw new \InvalidArgumentException('non-nullable record_type cannot be null');
        }
        $this->container['record_type'] = $record_type;

        return $this;
    }

    /**
     * Gets record_status
     *
     * @return string|null
     */
    public function getRecordStatus()
    {
        return $this->container['record_status'];
    }

    /**
     * Sets record_status
     *
     * @param string|null $record_status Current status of the record (e.g., Record Incomplete, Record Complete)
     *
     * @return self
     */
    public function setRecordStatus($record_status)
    {
        if (is_null($record_status)) {
            throw new \InvalidArgumentException('non-nullable record_status cannot be null');
        }
        $this->container['record_status'] = $record_status;

        return $this;
    }

    /**
     * Gets deleted
     *
     * @return bool|null
     */
    public function getDeleted()
    {
        return $this->container['deleted'];
    }

    /**
     * Sets deleted
     *
     * @param bool|null $deleted Whether the record is marked as deleted
     *
     * @return self
     */
    public function setDeleted($deleted)
    {
        if (is_null($deleted)) {
            throw new \InvalidArgumentException('non-nullable deleted cannot be null');
        }
        $this->container['deleted'] = $deleted;

        return $this;
    }

    /**
     * Gets date_created
     *
     * @return string|null
     */
    public function getDateCreated()
    {
        return $this->container['date_created'];
    }

    /**
     * Sets date_created
     *
     * @param string|null $date_created Date when this record was created
     *
     * @return self
     */
    public function setDateCreated($date_created)
    {
        if (is_null($date_created)) {
            throw new \InvalidArgumentException('non-nullable date_created cannot be null');
        }
        $this->container['date_created'] = $date_created;

        return $this;
    }

    /**
     * Gets date_modified
     *
     * @return string|null
     */
    public function getDateModified()
    {
        return $this->container['date_modified'];
    }

    /**
     * Sets date_modified
     *
     * @param string|null $date_modified Date when this record was last modified
     *
     * @return self
     */
    public function setDateModified($date_modified)
    {
        if (is_null($date_modified)) {
            throw new \InvalidArgumentException('non-nullable date_modified cannot be null');
        }
        $this->container['date_modified'] = $date_modified;

        return $this;
    }

    /**
     * Gets subject_id
     *
     * @return int|null
     */
    public function getSubjectId()
    {
        return $this->container['subject_id'];
    }

    /**
     * Sets subject_id
     *
     * @param int|null $subject_id Mednet subject ID that this record is associated with
     *
     * @return self
     */
    public function setSubjectId($subject_id)
    {
        if (is_null($subject_id)) {
            throw new \InvalidArgumentException('non-nullable subject_id cannot be null');
        }
        $this->container['subject_id'] = $subject_id;

        return $this;
    }

    /**
     * Gets subject_oid
     *
     * @return string|null
     */
    public function getSubjectOid()
    {
        return $this->container['subject_oid'];
    }

    /**
     * Sets subject_oid
     *
     * @param string|null $subject_oid Client-assigned subject OID for the subject this record is associated with
     *
     * @return self
     */
    public function setSubjectOid($subject_oid)
    {
        if (is_null($subject_oid)) {
            throw new \InvalidArgumentException('non-nullable subject_oid cannot be null');
        }
        $this->container['subject_oid'] = $subject_oid;

        return $this;
    }

    /**
     * Gets subject_key
     *
     * @return string|null
     */
    public function getSubjectKey()
    {
        return $this->container['subject_key'];
    }

    /**
     * Sets subject_key
     *
     * @param string|null $subject_key Subject display ID that this record is associated with
     *
     * @return self
     */
    public function setSubjectKey($subject_key)
    {
        if (is_null($subject_key)) {
            throw new \InvalidArgumentException('non-nullable subject_key cannot be null');
        }
        $this->container['subject_key'] = $subject_key;

        return $this;
    }

    /**
     * Gets visit_id
     *
     * @return int|null
     */
    public function getVisitId()
    {
        return $this->container['visit_id'];
    }

    /**
     * Sets visit_id
     *
     * @param int|null $visit_id Visit instance ID that this record is associated with (if applicable)
     *
     * @return self
     */
    public function setVisitId($visit_id)
    {
        if (is_null($visit_id)) {
            throw new \InvalidArgumentException('non-nullable visit_id cannot be null');
        }
        $this->container['visit_id'] = $visit_id;

        return $this;
    }

    /**
     * Gets parent_record_id
     *
     * @return int|null
     */
    public function getParentRecordId()
    {
        return $this->container['parent_record_id'];
    }

    /**
     * Sets parent_record_id
     *
     * @param int|null $parent_record_id Record ID of the parent record if this record is a subrecord (if applicable)
     *
     * @return self
     */
    public function setParentRecordId($parent_record_id)
    {
        if (is_null($parent_record_id)) {
            throw new \InvalidArgumentException('non-nullable parent_record_id cannot be null');
        }
        $this->container['parent_record_id'] = $parent_record_id;

        return $this;
    }

    /**
     * Gets keywords
     *
     * @return \OpenAPI\Client\Model\Keyword[]|null
     */
    public function getKeywords()
    {
        return $this->container['keywords'];
    }

    /**
     * Sets keywords
     *
     * @param \OpenAPI\Client\Model\Keyword[]|null $keywords List of keywords associated with the record
     *
     * @return self
     */
    public function setKeywords($keywords)
    {
        if (is_null($keywords)) {
            throw new \InvalidArgumentException('non-nullable keywords cannot be null');
        }
        $this->container['keywords'] = $keywords;

        return $this;
    }

    /**
     * Gets record_data
     *
     * @return array<string,mixed>|null
     */
    public function getRecordData()
    {
        return $this->container['record_data'];
    }

    /**
     * Sets record_data
     *
     * @param array<string,mixed>|null $record_data Data fields and values captured in this record. The structure is dynamic, with keys corresponding to variable names.
     *
     * @return self
     */
    public function setRecordData($record_data)
    {
        if (is_null($record_data)) {
            throw new \InvalidArgumentException('non-nullable record_data cannot be null');
        }
        $this->container['record_data'] = $record_data;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


