//
// StudiesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class StudiesAPI {

    /**
     List studies accessible by API key
     
     - parameter page: (query) Page index to retrieve (0-based) (optional, default to 0)
     - parameter size: (query) Number of items to return per page (max 500) (optional, default to 25)
     - parameter sort: (query) Sorting criteria in the format &#x60;property,ASC&#x60; or &#x60;property,DESC&#x60;. Can be repeated. (optional)
     - parameter filter: (query) Optional filter criteria to apply, in the format &#x60;attribute&#x3D;&#x3D;value&#x60; with support for &gt;, &gt;&#x3D;, &lt;, &lt;&#x3D;, !&#x3D;. Multiple criteria can be combined with &#x60;;&#x60; (AND) or &#x60;,&#x60; (OR). (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: StudyList
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listStudies(page: Int? = nil, size: Int? = nil, sort: String? = nil, filter: String? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> StudyList {
        return try await listStudiesWithRequestBuilder(page: page, size: size, sort: sort, filter: filter, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List studies accessible by API key
     - GET /studies
     - API Key:
       - type: apiKey x-api-key (HEADER)
       - name: apiKeyAuth
     - API Key:
       - type: apiKey x-imn-security-key (HEADER)
       - name: securityKeyAuth
     - parameter page: (query) Page index to retrieve (0-based) (optional, default to 0)
     - parameter size: (query) Number of items to return per page (max 500) (optional, default to 25)
     - parameter sort: (query) Sorting criteria in the format &#x60;property,ASC&#x60; or &#x60;property,DESC&#x60;. Can be repeated. (optional)
     - parameter filter: (query) Optional filter criteria to apply, in the format &#x60;attribute&#x3D;&#x3D;value&#x60; with support for &gt;, &gt;&#x3D;, &lt;, &lt;&#x3D;, !&#x3D;. Multiple criteria can be combined with &#x60;;&#x60; (AND) or &#x60;,&#x60; (OR). (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<StudyList> 
     */
    open class func listStudiesWithRequestBuilder(page: Int? = nil, size: Int? = nil, sort: String? = nil, filter: String? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<StudyList> {
        let localVariablePath = "/studies"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "size": (wrappedValue: size?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "sort": (wrappedValue: sort?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "filter": (wrappedValue: filter?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<StudyList>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
