/*
 * Mednet EDC API
 * The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
 *
 * The version of the OpenAPI document: 1.3.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.*;

import javax.validation.constraints.*;
import javax.validation.Valid;
import io.micronaut.core.annotation.*;
import javax.annotation.Generated;

/**
 * Job
 */
@JsonPropertyOrder({
  Job.JSON_PROPERTY_JOB_ID,
  Job.JSON_PROPERTY_BATCH_ID,
  Job.JSON_PROPERTY_STATE,
  Job.JSON_PROPERTY_DATE_CREATED,
  Job.JSON_PROPERTY_DATE_STARTED,
  Job.JSON_PROPERTY_DATE_FINISHED
})
@JsonTypeName("Job")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen", date="2025-07-14T13:50:33.483639736Z[Etc/UTC]", comments = "Generator version: 7.14.0")
@Introspected
public class Job {
    public static final String JSON_PROPERTY_JOB_ID = "jobId";
    private String jobId;

    public static final String JSON_PROPERTY_BATCH_ID = "batchId";
    private String batchId;

    public static final String JSON_PROPERTY_STATE = "state";
    private String state;

    public static final String JSON_PROPERTY_DATE_CREATED = "dateCreated";
    private String dateCreated;

    public static final String JSON_PROPERTY_DATE_STARTED = "dateStarted";
    private String dateStarted;

    public static final String JSON_PROPERTY_DATE_FINISHED = "dateFinished";
    private String dateFinished;

    public Job() {
    }

    public Job jobId(String jobId) {
        this.jobId = jobId;
        return this;
    }

    /**
     * Unique job identifier
     * @return jobId
     */
    @Nullable
    @JsonProperty(JSON_PROPERTY_JOB_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getJobId() {
        return jobId;
    }

    @JsonProperty(JSON_PROPERTY_JOB_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setJobId(String jobId) {
        this.jobId = jobId;
    }

    public Job batchId(String batchId) {
        this.batchId = batchId;
        return this;
    }

    /**
     * Batch ID associated with the job (useful for linking with record creation requests)
     * @return batchId
     */
    @Nullable
    @JsonProperty(JSON_PROPERTY_BATCH_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getBatchId() {
        return batchId;
    }

    @JsonProperty(JSON_PROPERTY_BATCH_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setBatchId(String batchId) {
        this.batchId = batchId;
    }

    public Job state(String state) {
        this.state = state;
        return this;
    }

    /**
     * State of the job (e.g., completed, pending)
     * @return state
     */
    @Nullable
    @JsonProperty(JSON_PROPERTY_STATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getState() {
        return state;
    }

    @JsonProperty(JSON_PROPERTY_STATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setState(String state) {
        this.state = state;
    }

    public Job dateCreated(String dateCreated) {
        this.dateCreated = dateCreated;
        return this;
    }

    /**
     * Timestamp when the job was created
     * @return dateCreated
     */
    @Nullable
    @JsonProperty(JSON_PROPERTY_DATE_CREATED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getDateCreated() {
        return dateCreated;
    }

    @JsonProperty(JSON_PROPERTY_DATE_CREATED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDateCreated(String dateCreated) {
        this.dateCreated = dateCreated;
    }

    public Job dateStarted(String dateStarted) {
        this.dateStarted = dateStarted;
        return this;
    }

    /**
     * Timestamp when the job started processing
     * @return dateStarted
     */
    @Nullable
    @JsonProperty(JSON_PROPERTY_DATE_STARTED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getDateStarted() {
        return dateStarted;
    }

    @JsonProperty(JSON_PROPERTY_DATE_STARTED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDateStarted(String dateStarted) {
        this.dateStarted = dateStarted;
    }

    public Job dateFinished(String dateFinished) {
        this.dateFinished = dateFinished;
        return this;
    }

    /**
     * Timestamp when the job finished processing
     * @return dateFinished
     */
    @Nullable
    @JsonProperty(JSON_PROPERTY_DATE_FINISHED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getDateFinished() {
        return dateFinished;
    }

    @JsonProperty(JSON_PROPERTY_DATE_FINISHED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDateFinished(String dateFinished) {
        this.dateFinished = dateFinished;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Job job = (Job) o;
        return Objects.equals(this.jobId, job.jobId) &&
            Objects.equals(this.batchId, job.batchId) &&
            Objects.equals(this.state, job.state) &&
            Objects.equals(this.dateCreated, job.dateCreated) &&
            Objects.equals(this.dateStarted, job.dateStarted) &&
            Objects.equals(this.dateFinished, job.dateFinished);
    }

    @Override
    public int hashCode() {
        return Objects.hash(jobId, batchId, state, dateCreated, dateStarted, dateFinished);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Job {\n");
        sb.append("    jobId: ").append(toIndentedString(jobId)).append("\n");
        sb.append("    batchId: ").append(toIndentedString(batchId)).append("\n");
        sb.append("    state: ").append(toIndentedString(state)).append("\n");
        sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
        sb.append("    dateStarted: ").append(toIndentedString(dateStarted)).append("\n");
        sb.append("    dateFinished: ").append(toIndentedString(dateFinished)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

