--[[
  Mednet EDC API

  The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 

  The version of the OpenAPI document: 1.3.6
  
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for openapiclient.model.keyword
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("keyword", function()
  local openapiclient_keyword = require "openapiclient.model.keyword"

  -- unit tests for the property 'keyword_name'
  describe("property keyword_name test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'keyword_key'
  describe("property keyword_key test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'keyword_id'
  describe("property keyword_id test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'date_added'
  describe("property date_added test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
