=begin comment

Mednet EDC API

The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 

The version of the OpenAPI document: 1.3.6

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::JobsApi;

require 5.6.0;
use strict;
use warnings;
use utf8;
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::OpenAPIClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::OpenAPIClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::OpenAPIClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# get_job_status
#
# Retrieve job status by batch ID
#
# @param string $study_key Study key identifying the study context for the request (required)
# @param string $batch_id Batch ID of the job to retrieve (required)
{
    my $params = {
    'study_key' => {
        data_type => 'string',
        description => 'Study key identifying the study context for the request',
        required => '1',
    },
    'batch_id' => {
        data_type => 'string',
        description => 'Batch ID of the job to retrieve',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_job_status' } = {
        summary => 'Retrieve job status by batch ID',
        params => $params,
        returns => 'Job',
        };
}
# @return Job
#
sub get_job_status {
    my ($self, %args) = @_;

    # verify the required parameter 'study_key' is set
    unless (exists $args{'study_key'}) {
      croak("Missing the required parameter 'study_key' when calling get_job_status");
    }

    # verify the required parameter 'batch_id' is set
    unless (exists $args{'batch_id'}) {
      croak("Missing the required parameter 'batch_id' when calling get_job_status");
    }

    # parse inputs
    my $_resource_path = '/studies/{studyKey}/jobs/{batchId}';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'study_key'}) {
        my $_base_variable = "{" . "studyKey" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'study_key'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    # path params
    if ( exists $args{'batch_id'}) {
        my $_base_variable = "{" . "batchId" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'batch_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(apiKeyAuth securityKeyAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('Job', $response);
    return $_response_object;
}

1;
