// tslint:disable
/**
 * Mednet EDC API
 * The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
 *
 * The version of the OpenAPI document: 1.3.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ComponentsSchemasRecordCreateRequestItem
 */
export interface ComponentsSchemasRecordCreateRequestItem {
    /**
     * Form key identifying the eCRF to create or update
     * @type {string}
     * @memberof ComponentsSchemasRecordCreateRequestItem
     */
    formKey: string;
    /**
     * Form ID identifying the eCRF to create or update (alternative to formKey)
     * @type {number}
     * @memberof ComponentsSchemasRecordCreateRequestItem
     */
    formId?: number;
    /**
     * Name of the site where the record should be created (for new subject registration)
     * @type {string}
     * @memberof ComponentsSchemasRecordCreateRequestItem
     */
    siteName?: string;
    /**
     * Site ID for the record (alternative to siteName)
     * @type {number}
     * @memberof ComponentsSchemasRecordCreateRequestItem
     */
    siteId?: number;
    /**
     * Subject identifier (display ID) for which to create or update the record
     * @type {string}
     * @memberof ComponentsSchemasRecordCreateRequestItem
     */
    subjectKey?: string;
    /**
     * Subject ID for which to create or update the record (alternative to subjectKey)
     * @type {number}
     * @memberof ComponentsSchemasRecordCreateRequestItem
     */
    subjectId?: number;
    /**
     * Subject OID for which to create or update the record (alternative to subjectKey)
     * @type {string}
     * @memberof ComponentsSchemasRecordCreateRequestItem
     */
    subjectOid?: string;
    /**
     * Name of the interval (visit) for a scheduled record update
     * @type {string}
     * @memberof ComponentsSchemasRecordCreateRequestItem
     */
    intervalName?: string;
    /**
     * Interval ID for a scheduled record update (alternative to intervalName)
     * @type {number}
     * @memberof ComponentsSchemasRecordCreateRequestItem
     */
    intervalId?: number;
    /**
     * Record ID for updating an existing unscheduled record (if applicable)
     * @type {number}
     * @memberof ComponentsSchemasRecordCreateRequestItem
     */
    recordId?: number;
    /**
     * Record OID for updating an existing unscheduled record (if applicable)
     * @type {string}
     * @memberof ComponentsSchemasRecordCreateRequestItem
     */
    recordOid?: string;
    /**
     * Key-value pairs of field names and values for the record data
     * @type {{ [key: string]: any; }}
     * @memberof ComponentsSchemasRecordCreateRequestItem
     */
    data: { [key: string]: any; };
}
