// tslint:disable
/**
 * Mednet EDC API
 * The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
 *
 * The version of the OpenAPI document: 1.3.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface Study
 */
export interface Study {
    /**
     * Sponsor key that this study belongs to
     * @type {string}
     * @memberof Study
     */
    sponsorKey?: string;
    /**
     * Unique study key
     * @type {string}
     * @memberof Study
     */
    studyKey?: string;
    /**
     * Mednet study ID (internal numeric identifier)
     * @type {number}
     * @memberof Study
     */
    studyId?: number;
    /**
     * Name of the study
     * @type {string}
     * @memberof Study
     */
    studyName?: string;
    /**
     * Description of the study
     * @type {string}
     * @memberof Study
     */
    studyDescription?: string;
    /**
     * Type of study (e.g., STUDY)
     * @type {string}
     * @memberof Study
     */
    studyType?: string;
    /**
     * Date when the study record was created
     * @type {string}
     * @memberof Study
     */
    dateCreated?: string;
    /**
     * Date when the study record was last modified
     * @type {string}
     * @memberof Study
     */
    dateModified?: string;
}
