# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct RecordRevisionsApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `RecordRevisionsApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ RecordRevisionsApi }) = "https://edc.prod.imednetapi.com/api/v1/edc"

const _returntypes_list_record_revisions_RecordRevisionsApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => RecordRevisionList,
    Regex("^" * replace("400", "x"=>".") * "\$") => InlineObject,
    Regex("^" * replace("401", "x"=>".") * "\$") => InlineObject1,
    Regex("^" * replace("403", "x"=>".") * "\$") => InlineObject2,
    Regex("^" * replace("404", "x"=>".") * "\$") => InlineObject3,
    Regex("^" * replace("500", "x"=>".") * "\$") => InlineObject5,
)

function _oacinternal_list_record_revisions(_api::RecordRevisionsApi, study_key::String; page=nothing, size=nothing, sort=nothing, filter=nothing, _mediaType=nothing)
    OpenAPI.validate_param("page", "list_record_revisions", :minimum, page, 0, false)

    OpenAPI.validate_param("size", "list_record_revisions", :maximum, size, 500, false)
    OpenAPI.validate_param("size", "list_record_revisions", :minimum, size, 1, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_list_record_revisions_RecordRevisionsApi, "/studies/{studyKey}/recordRevisions", ["apiKeyAuth", "securityKeyAuth", ])
    OpenAPI.Clients.set_param(_ctx.path, "studyKey", study_key)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "page", page; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "size", size; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "sort", sort; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "filter", filter; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""List record revisions (audit trail entries) in a study

Params:
- study_key::String (required)
- page::Int64
- size::Int64
- sort::String
- filter::String

Return: RecordRevisionList, OpenAPI.Clients.ApiResponse
"""
function list_record_revisions(_api::RecordRevisionsApi, study_key::String; page=nothing, size=nothing, sort=nothing, filter=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_record_revisions(_api, study_key; page=page, size=size, sort=sort, filter=filter, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function list_record_revisions(_api::RecordRevisionsApi, response_stream::Channel, study_key::String; page=nothing, size=nothing, sort=nothing, filter=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_record_revisions(_api, study_key; page=page, size=size, sort=sort, filter=filter, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export list_record_revisions
