#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Mednet EDC API
* The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
*
* The version of the OpenAPI document: 1.3.6
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIKeyword
@end

@interface OAIKeyword : OAIObject

/* Name of the keyword [optional]
 */
@property(nonatomic) NSString* keywordName;
/* Key of the keyword (short code) [optional]
 */
@property(nonatomic) NSString* keywordKey;
/* Internal keyword ID [optional]
 */
@property(nonatomic) NSNumber* keywordId;
/* Date when this keyword was added [optional]
 */
@property(nonatomic) NSString* dateAdded;

@end
