#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Mednet EDC API
* The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
*
* The version of the OpenAPI document: 1.3.6
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIKeyword.h"
@protocol OAIKeyword;
@class OAIKeyword;



@protocol OAISubject
@end

@interface OAISubject : OAIObject

/* Unique study key [optional]
 */
@property(nonatomic) NSString* studyKey;
/* Mednet subject ID (internal numeric ID) [optional]
 */
@property(nonatomic) NSNumber* subjectId;
/* Client-assigned subject object identifier (OID) [optional]
 */
@property(nonatomic) NSString* subjectOid;
/* Protocol-assigned subject identifier (display ID) [optional]
 */
@property(nonatomic) NSString* subjectKey;
/* Current status of the subject (e.g., Enrolled) [optional]
 */
@property(nonatomic) NSString* subjectStatus;
/* Mednet site ID the subject is associated with [optional]
 */
@property(nonatomic) NSNumber* siteId;
/* Name of the site the subject is associated with [optional]
 */
@property(nonatomic) NSString* siteName;
/* Whether the subject is marked as deleted [optional]
 */
@property(nonatomic) NSNumber* deleted;
/* Subject’s enrollment start date [optional]
 */
@property(nonatomic) NSString* enrollmentStartDate;
/* Date when this subject record was created [optional]
 */
@property(nonatomic) NSString* dateCreated;
/* Date when this subject record was last modified [optional]
 */
@property(nonatomic) NSString* dateModified;
/* List of keywords associated with the subject [optional]
 */
@property(nonatomic) NSArray<OAIKeyword>* keywords;

@end
