/* tslint:disable */
/* eslint-disable */
/**
 * Mednet EDC API
 * The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
 *
 * The version of the OpenAPI document: 1.3.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Study
 */
export interface Study {
    /**
     * Sponsor key that this study belongs to
     * @type {string}
     * @memberof Study
     */
    sponsorKey?: string;
    /**
     * Unique study key
     * @type {string}
     * @memberof Study
     */
    studyKey?: string;
    /**
     * Mednet study ID (internal numeric identifier)
     * @type {number}
     * @memberof Study
     */
    studyId?: number;
    /**
     * Name of the study
     * @type {string}
     * @memberof Study
     */
    studyName?: string;
    /**
     * Description of the study
     * @type {string}
     * @memberof Study
     */
    studyDescription?: string;
    /**
     * Type of study (e.g., STUDY)
     * @type {string}
     * @memberof Study
     */
    studyType?: string;
    /**
     * Date when the study record was created
     * @type {string}
     * @memberof Study
     */
    dateCreated?: string;
    /**
     * Date when the study record was last modified
     * @type {string}
     * @memberof Study
     */
    dateModified?: string;
}

/**
 * Check if a given object implements the Study interface.
 */
export function instanceOfStudy(value: object): value is Study {
    return true;
}

export function StudyFromJSON(json: any): Study {
    return StudyFromJSONTyped(json, false);
}

export function StudyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Study {
    if (json == null) {
        return json;
    }
    return {
        
        'sponsorKey': json['sponsorKey'] == null ? undefined : json['sponsorKey'],
        'studyKey': json['studyKey'] == null ? undefined : json['studyKey'],
        'studyId': json['studyId'] == null ? undefined : json['studyId'],
        'studyName': json['studyName'] == null ? undefined : json['studyName'],
        'studyDescription': json['studyDescription'] == null ? undefined : json['studyDescription'],
        'studyType': json['studyType'] == null ? undefined : json['studyType'],
        'dateCreated': json['dateCreated'] == null ? undefined : json['dateCreated'],
        'dateModified': json['dateModified'] == null ? undefined : json['dateModified'],
    };
}

export function StudyToJSON(json: any): Study {
    return StudyToJSONTyped(json, false);
}

export function StudyToJSONTyped(value?: Study | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sponsorKey': value['sponsorKey'],
        'studyKey': value['studyKey'],
        'studyId': value['studyId'],
        'studyName': value['studyName'],
        'studyDescription': value['studyDescription'],
        'studyType': value['studyType'],
        'dateCreated': value['dateCreated'],
        'dateModified': value['dateModified'],
    };
}

