/* tslint:disable */
/* eslint-disable */
/**
 * Mednet EDC API
 * The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
 *
 * The version of the OpenAPI document: 1.3.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
    PaginationToJSONTyped,
} from './Pagination';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { Metadata } from './Metadata';
import {
    MetadataFromJSON,
    MetadataFromJSONTyped,
    MetadataToJSON,
    MetadataToJSONTyped,
} from './Metadata';

/**
 * 
 * @export
 * @interface UserList
 */
export interface UserList {
    /**
     * 
     * @type {Metadata}
     * @memberof UserList
     */
    metadata?: Metadata;
    /**
     * 
     * @type {Pagination}
     * @memberof UserList
     */
    pagination?: Pagination;
    /**
     * 
     * @type {Array<User>}
     * @memberof UserList
     */
    data?: Array<User>;
}

/**
 * Check if a given object implements the UserList interface.
 */
export function instanceOfUserList(value: object): value is UserList {
    return true;
}

export function UserListFromJSON(json: any): UserList {
    return UserListFromJSONTyped(json, false);
}

export function UserListFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserList {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': json['metadata'] == null ? undefined : MetadataFromJSON(json['metadata']),
        'pagination': json['pagination'] == null ? undefined : PaginationFromJSON(json['pagination']),
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(UserFromJSON)),
    };
}

export function UserListToJSON(json: any): UserList {
    return UserListToJSONTyped(json, false);
}

export function UserListToJSONTyped(value?: UserList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metadata': MetadataToJSON(value['metadata']),
        'pagination': PaginationToJSON(value['pagination']),
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(UserToJSON)),
    };
}

