# NOTE: This file is auto generated by OpenAPI Generator 7.14.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MednetEDCAPI.Model.Role do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :dateCreated,
    :dateModified,
    :roleId,
    :communityId,
    :name,
    :description,
    :level,
    :type,
    :inactive
  ]

  @type t :: %__MODULE__{
    :dateCreated => [integer()] | nil,
    :dateModified => [integer()] | nil,
    :roleId => String.t | nil,
    :communityId => integer() | nil,
    :name => String.t | nil,
    :description => String.t | nil,
    :level => integer() | nil,
    :type => String.t | nil,
    :inactive => boolean() | nil
  }

  def decode(value) do
    value
  end
end

