## QueriesApi

### List data queries in a study
## List data queries in a study
GET https://edc.prod.imednetapi.com/api/v1/edc/studies/{{studyKey}}/queries?page={{page}}&size={{size}}&sort={{sort}}&filter={{filter}}
Accept: application/json
x-api-key: {{apiKey}}
x-imn-security-key: {{apiKey}}
