/**
 * Mednet EDC API
 * The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
 *
 * The version of the OpenAPI document: 1.3.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.Interval;
import org.openapitools.client.model.Metadata;
import org.openapitools.client.model.Pagination;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class IntervalList {
  
  @SerializedName("metadata")
  private Metadata metadata = null;
  @SerializedName("pagination")
  private Pagination pagination = null;
  @SerializedName("data")
  private List<Interval> data = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Metadata getMetadata() {
    return metadata;
  }
  public void setMetadata(Metadata metadata) {
    this.metadata = metadata;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Pagination getPagination() {
    return pagination;
  }
  public void setPagination(Pagination pagination) {
    this.pagination = pagination;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Interval> getData() {
    return data;
  }
  public void setData(List<Interval> data) {
    this.data = data;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IntervalList intervalList = (IntervalList) o;
    return (this.metadata == null ? intervalList.metadata == null : this.metadata.equals(intervalList.metadata)) &&
        (this.pagination == null ? intervalList.pagination == null : this.pagination.equals(intervalList.pagination)) &&
        (this.data == null ? intervalList.data == null : this.data.equals(intervalList.data));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.metadata == null ? 0: this.metadata.hashCode());
    result = 31 * result + (this.pagination == null ? 0: this.pagination.hashCode());
    result = 31 * result + (this.data == null ? 0: this.data.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class IntervalList {\n");
    
    sb.append("  metadata: ").append(metadata).append("\n");
    sb.append("  pagination: ").append(pagination).append("\n");
    sb.append("  data: ").append(data).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
