/**
 * Mednet EDC API
 * The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
 *
 * The version of the OpenAPI document: 1.3.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.Date;
import org.openapitools.client.model.ComponentsSchemasMetadataError;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Metadata {
  
  @SerializedName("status")
  private String status = null;
  @SerializedName("method")
  private String method = null;
  @SerializedName("path")
  private String path = null;
  @SerializedName("timestamp")
  private Date timestamp = null;
  @SerializedName("error")
  private ComponentsSchemasMetadataError error = null;

  /**
   * HTTP status of the response (e.g., OK or ERROR)
   **/
  @ApiModelProperty(value = "HTTP status of the response (e.g., OK or ERROR)")
  public String getStatus() {
    return status;
  }
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   * HTTP method of the request
   **/
  @ApiModelProperty(value = "HTTP method of the request")
  public String getMethod() {
    return method;
  }
  public void setMethod(String method) {
    this.method = method;
  }

  /**
   * Requested URI path
   **/
  @ApiModelProperty(value = "Requested URI path")
  public String getPath() {
    return path;
  }
  public void setPath(String path) {
    this.path = path;
  }

  /**
   * Timestamp when response was generated
   **/
  @ApiModelProperty(value = "Timestamp when response was generated")
  public Date getTimestamp() {
    return timestamp;
  }
  public void setTimestamp(Date timestamp) {
    this.timestamp = timestamp;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ComponentsSchemasMetadataError getError() {
    return error;
  }
  public void setError(ComponentsSchemasMetadataError error) {
    this.error = error;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Metadata metadata = (Metadata) o;
    return (this.status == null ? metadata.status == null : this.status.equals(metadata.status)) &&
        (this.method == null ? metadata.method == null : this.method.equals(metadata.method)) &&
        (this.path == null ? metadata.path == null : this.path.equals(metadata.path)) &&
        (this.timestamp == null ? metadata.timestamp == null : this.timestamp.equals(metadata.timestamp)) &&
        (this.error == null ? metadata.error == null : this.error.equals(metadata.error));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.method == null ? 0: this.method.hashCode());
    result = 31 * result + (this.path == null ? 0: this.path.hashCode());
    result = 31 * result + (this.timestamp == null ? 0: this.timestamp.hashCode());
    result = 31 * result + (this.error == null ? 0: this.error.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Metadata {\n");
    
    sb.append("  status: ").append(status).append("\n");
    sb.append("  method: ").append(method).append("\n");
    sb.append("  path: ").append(path).append("\n");
    sb.append("  timestamp: ").append(timestamp).append("\n");
    sb.append("  error: ").append(error).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
