/**
 * Mednet EDC API
 * The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
 *
 * The version of the OpenAPI document: 1.3.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;




public class Site  {
  
 /**
   * Unique study key
  **/
  private String studyKey;

 /**
   * Unique site ID
  **/
  private Integer siteId;

 /**
   * Name of the site
  **/
  private String siteName;

 /**
   * Enrollment status of the site
  **/
  private String siteEnrollmentStatus;

 /**
   * Date when this site was created
  **/
  private String dateCreated;

 /**
   * Date when this site was last modified
  **/
  private String dateModified;

 /**
   * Unique study key
   * @return studyKey
  **/
  public String getStudyKey() {
    return studyKey;
  }

  /**
    * Set studyKey
  **/
  public void setStudyKey(String studyKey) {
    this.studyKey = studyKey;
  }

  public Site studyKey(String studyKey) {
    this.studyKey = studyKey;
    return this;
  }

 /**
   * Unique site ID
   * @return siteId
  **/
  public Integer getSiteId() {
    return siteId;
  }

  /**
    * Set siteId
  **/
  public void setSiteId(Integer siteId) {
    this.siteId = siteId;
  }

  public Site siteId(Integer siteId) {
    this.siteId = siteId;
    return this;
  }

 /**
   * Name of the site
   * @return siteName
  **/
  public String getSiteName() {
    return siteName;
  }

  /**
    * Set siteName
  **/
  public void setSiteName(String siteName) {
    this.siteName = siteName;
  }

  public Site siteName(String siteName) {
    this.siteName = siteName;
    return this;
  }

 /**
   * Enrollment status of the site
   * @return siteEnrollmentStatus
  **/
  public String getSiteEnrollmentStatus() {
    return siteEnrollmentStatus;
  }

  /**
    * Set siteEnrollmentStatus
  **/
  public void setSiteEnrollmentStatus(String siteEnrollmentStatus) {
    this.siteEnrollmentStatus = siteEnrollmentStatus;
  }

  public Site siteEnrollmentStatus(String siteEnrollmentStatus) {
    this.siteEnrollmentStatus = siteEnrollmentStatus;
    return this;
  }

 /**
   * Date when this site was created
   * @return dateCreated
  **/
  public String getDateCreated() {
    return dateCreated;
  }

  /**
    * Set dateCreated
  **/
  public void setDateCreated(String dateCreated) {
    this.dateCreated = dateCreated;
  }

  public Site dateCreated(String dateCreated) {
    this.dateCreated = dateCreated;
    return this;
  }

 /**
   * Date when this site was last modified
   * @return dateModified
  **/
  public String getDateModified() {
    return dateModified;
  }

  /**
    * Set dateModified
  **/
  public void setDateModified(String dateModified) {
    this.dateModified = dateModified;
  }

  public Site dateModified(String dateModified) {
    this.dateModified = dateModified;
    return this;
  }


  /**
    * Create a string representation of this pojo.
  **/
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Site {\n");
    
    sb.append("    studyKey: ").append(toIndentedString(studyKey)).append("\n");
    sb.append("    siteId: ").append(toIndentedString(siteId)).append("\n");
    sb.append("    siteName: ").append(toIndentedString(siteName)).append("\n");
    sb.append("    siteEnrollmentStatus: ").append(toIndentedString(siteEnrollmentStatus)).append("\n");
    sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
    sb.append("    dateModified: ").append(toIndentedString(dateModified)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

