// tslint:disable
/**
 * Mednet EDC API
 * The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
 *
 * The version of the OpenAPI document: 1.3.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Metadata,
    MetadataFromJSON,
    MetadataToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineObject3
 */
export interface InlineObject3  {
    /**
     * 
     * @type {Metadata}
     * @memberof InlineObject3
     */
    metadata?: Metadata;
}

export function InlineObject3FromJSON(json: any): InlineObject3 {
    return {
        'metadata': !exists(json, 'metadata') ? undefined : MetadataFromJSON(json['metadata']),
    };
}

export function InlineObject3ToJSON(value?: InlineObject3): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'metadata': MetadataToJSON(value.metadata),
    };
}


