# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""inline_object_4

    InlineObject4(;
        metadata=nothing,
    )

    - metadata::Metadata
"""
Base.@kwdef mutable struct InlineObject4 <: OpenAPI.APIModel
    metadata = nothing # spec type: Union{ Nothing, Metadata }

    function InlineObject4(metadata, )
        o = new(metadata, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type InlineObject4

const _property_types_InlineObject4 = Dict{Symbol,String}(Symbol("metadata")=>"Metadata", )
OpenAPI.property_type(::Type{ InlineObject4 }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_InlineObject4[name]))}

function OpenAPI.check_required(o::InlineObject4)
    true
end

function OpenAPI.validate_properties(o::InlineObject4)
    OpenAPI.validate_property(InlineObject4, Symbol("metadata"), o.metadata)
end

function OpenAPI.validate_property(::Type{ InlineObject4 }, name::Symbol, val)

end
