#
# Mednet EDC API
# 
# The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
# The version of the OpenAPI document: 1.3.6
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables

import model_coding
import model_metadata
import model_pagination

type CodingList* = object
  ## 
  metadata*: Metadata
  pagination*: Pagination
  data*: seq[Coding]
