--[[
  Mednet EDC API

  The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 

  The version of the OpenAPI document: 1.3.6
  
  Generated by: https://openapi-generator.tech
]]

-- metadata class
local metadata = {}
local metadata_mt = {
	__name = "metadata";
	__index = metadata;
}

local function cast_metadata(t)
	return setmetatable(t, metadata_mt)
end

local function new_metadata(status, method, path, timestamp, error)
	return cast_metadata({
		["status"] = status;
		["method"] = method;
		["path"] = path;
		["timestamp"] = timestamp;
		["error"] = error;
	})
end

return {
	cast = cast_metadata;
	new = new_metadata;
}
