export * from './administration.service';
import { AdministrationService } from './administration.service';
export * from './codings.service';
import { CodingsService } from './codings.service';
export * from './forms.service';
import { FormsService } from './forms.service';
export * from './intervals.service';
import { IntervalsService } from './intervals.service';
export * from './jobs.service';
import { JobsService } from './jobs.service';
export * from './queries.service';
import { QueriesService } from './queries.service';
export * from './recordRevisions.service';
import { RecordRevisionsService } from './recordRevisions.service';
export * from './records.service';
import { RecordsService } from './records.service';
export * from './sites.service';
import { SitesService } from './sites.service';
export * from './studies.service';
import { StudiesService } from './studies.service';
export * from './subjects.service';
import { SubjectsService } from './subjects.service';
export * from './variables.service';
import { VariablesService } from './variables.service';
export * from './visits.service';
import { VisitsService } from './visits.service';
export const APIS = [AdministrationService, CodingsService, FormsService, IntervalsService, JobsService, QueriesService, RecordRevisionsService, RecordsService, SitesService, StudiesService, SubjectsService, VariablesService, VisitsService];
