/**
 * Mednet EDC API
 * The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
 *
 * The version of the OpenAPI document: 1.3.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ComponentsSchemasIntervalFormsItem model module.
 * @module model/ComponentsSchemasIntervalFormsItem
 * @version 1.3.6
 */
class ComponentsSchemasIntervalFormsItem {
    /**
     * @member {Number} formId
     * @type {Number}
     */
    formId;
    /**
     * @member {String} formKey
     * @type {String}
     */
    formKey;
    /**
     * @member {String} formName
     * @type {String}
     */
    formName;

    

    /**
     * Constructs a new <code>ComponentsSchemasIntervalFormsItem</code>.
     * @alias module:model/ComponentsSchemasIntervalFormsItem
     */
    constructor() { 
        
        ComponentsSchemasIntervalFormsItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ComponentsSchemasIntervalFormsItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ComponentsSchemasIntervalFormsItem} obj Optional instance to populate.
     * @return {module:model/ComponentsSchemasIntervalFormsItem} The populated <code>ComponentsSchemasIntervalFormsItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ComponentsSchemasIntervalFormsItem();

            if (data.hasOwnProperty('formId')) {
                obj['formId'] = ApiClient.convertToType(data['formId'], 'Number');
            }
            if (data.hasOwnProperty('formKey')) {
                obj['formKey'] = ApiClient.convertToType(data['formKey'], 'String');
            }
            if (data.hasOwnProperty('formName')) {
                obj['formName'] = ApiClient.convertToType(data['formName'], 'String');
            }
        }
        return obj;
    }
}



export default ComponentsSchemasIntervalFormsItem;

