export * from './AdministrationApi';
import { AdministrationApi } from './AdministrationApi';
export * from './CodingsApi';
import { CodingsApi } from './CodingsApi';
export * from './FormsApi';
import { FormsApi } from './FormsApi';
export * from './IntervalsApi';
import { IntervalsApi } from './IntervalsApi';
export * from './JobsApi';
import { JobsApi } from './JobsApi';
export * from './QueriesApi';
import { QueriesApi } from './QueriesApi';
export * from './RecordRevisionsApi';
import { RecordRevisionsApi } from './RecordRevisionsApi';
export * from './RecordsApi';
import { RecordsApi } from './RecordsApi';
export * from './SitesApi';
import { SitesApi } from './SitesApi';
export * from './StudiesApi';
import { StudiesApi } from './StudiesApi';
export * from './SubjectsApi';
import { SubjectsApi } from './SubjectsApi';
export * from './VariablesApi';
import { VariablesApi } from './VariablesApi';
export * from './VisitsApi';
import { VisitsApi } from './VisitsApi';
export const APIS = [AdministrationApi, CodingsApi, FormsApi, IntervalsApi, JobsApi, QueriesApi, RecordRevisionsApi, RecordsApi, SitesApi, StudiesApi, SubjectsApi, VariablesApi, VisitsApi];
