/**
 * Mednet EDC API
 * The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
 *
 * OpenAPI spec version: 1.3.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ComponentsSchemasIntervalFormsItem {
    /**
    * Form ID scheduled in the interval
    */
    'formId'?: number;
    /**
    * Form key scheduled in the interval
    */
    'formKey'?: string;
    /**
    * Form name scheduled in the interval
    */
    'formName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "formId",
            "baseName": "formId",
            "type": "number",
            "format": ""
        },
        {
            "name": "formKey",
            "baseName": "formKey",
            "type": "string",
            "format": ""
        },
        {
            "name": "formName",
            "baseName": "formName",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ComponentsSchemasIntervalFormsItem.attributeTypeMap;
    }

    public constructor() {
    }
}
